stages:
  preprocess:
    cmd: python -m src.train
    deps:
    - data/test_data.csv
    - data/train_data.csv
    - src/train.py
    outs:
    - experiments/svc/model.pkl
    metrics:
    - experiments/svc/metrics.json
